
int incByValue(int number);
int incByPointer(int* number);
int incByReference(int &number);
void swapPtr(int* ptrA, int* ptrB);
void swapRef(int &refA, int &refB);
int minInArray(const int* arr, const int arrSize);
int minIn2DArray(const int* arr, const int arrRows, const int arrColums);
int myStrCmp(const char* str1, const char* str2);
int dayOfYear(int day, int month, int year, int* table);
int* dayOfMonth(int dayOfTheYear, int year, int* table);
void addUnique(int* arr, int i, int n, int newValue);
void printArray(int* arr, int n);
int sumN(int n);
int encoded32Size(int rawSize);
int decoded32Size(int encodeSize);
int encode32(char *rawData, int rawSize, char *dst);
int decode32(char *encodedData, int encodedSize, char *dst);
char* encodeString(char* string);
char* decodeString(char* encodedStrig);